name: Validate JSON

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validation script
        run: python3 ${{github.workspace}}/.github/validate.py ${{github.workspace}}/articles.json

